### PR TITLE
Branch 23.08

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
Probably doesn't make sense, because node v16 just EOL-ed this month https://nodejs.dev/en/about/releases/, just noticed.

**Comment by Zishan-Rahman** [comment]
> Probably doesn't make sense, because node v16 just EOL-ed this month https://nodejs.dev/en/about/releases/, just noticed.

@bbhtt Sorry for the ping. Just wanted to chime in with my view on this, as I still believe a 23.08 branch should be created.

Currently I have this PR, flathub/org.freedesktop.Sdk.Extension.node14#48, which I setup because of _another_ PR, flathub/com.wickeditor.WickEditor#2, in which trying to build the test Wick Editor build with the new runtime and the Node.js 18 extension fails due to a problem I described in flathub/org.freedesktop.Sdk.Extension.node18#40.

Therefore, I'd say that, for applications that still require Node.js 16 to build properly (and 14, for that matter), it may be a good idea to set up the 23.08 branch for those extensions anyway, so that apps using it can still use them while updating their runtimes and SDKs, at least until they're able to migrate to a currently supported version of Node.js without much hassle. This is purely my opinion, though. Whether or not a 23.08 branch should be created for this Node.js 16 extension is up to you. I'll very much appreciate any response and feedback you have towards my comment.

Sidenote: As of now, the test Node.js 14 extension build for flathub/org.freedesktop.Sdk.Extension.node14#48 _also fails_, [due to the version of Python used by Buildbot in this case being too recent](https://github.com/flathub/org.freedesktop.Sdk.Extension.node14/pull/48#issuecomment-1738094943). No idea why _that_ happened.

**Comment by bbhtt** [comment]
I can create the branch but (cc) @gasinvein is the maintainer here.

**Comment by bbhtt** [comment]
> Currently I have this PR, https://github.com/flathub/org.freedesktop.Sdk.Extension.node14/pull/48, which I setup because of another PR, https://github.com/flathub/com.wickeditor.WickEditor/pull/2, in which trying to build the test Wick Editor build with the new runtime and the Node.js 18 extension fails due to a problem I described in https://github.com/flathub/org.freedesktop.Sdk.Extension.node18/issues/40.

You forgot to change the path of the SDK there, commented. https://github.com/flathub/com.wickeditor.WickEditor/pull/2/files#r1340490900

**Comment by Zishan-Rahman** [comment]
> > Currently I have this PR, [flathub/org.freedesktop.Sdk.Extension.node14#48](https://github.com/flathub/org.freedesktop.Sdk.Extension.node14/pull/48), which I setup because of another PR, [flathub/com.wickeditor.WickEditor#2](https://github.com/flathub/com.wickeditor.WickEditor/pull/2), in which trying to build the test Wick Editor build with the new runtime and the Node.js 18 extension fails due to a problem I described in [flathub/org.freedesktop.Sdk.Extension.node18#40](https://github.com/flathub/org.freedesktop.Sdk.Extension.node18/issues/40).
> 
> You forgot to change the path of the SDK there, commented. https://github.com/flathub/com.wickeditor.WickEditor/pull/2/files#r1340490900

How on Earth did I forget to change the `append-path`? :man_facepalming: 

[I went and changed it just now.](https://github.com/flathub/com.wickeditor.WickEditor/pull/2/commits/c635ab690bccbe790e8d0b548ec29cc8718fb6be)

**Pull request closed without merging**
